baseURL = "https://efalconhndz.github.io/"
languageCode = "en-us"
title = "Emanuel Falcón"

[params]
    firstName = "Emanuel"
    lastName = "Falcón"
    address = "Kansas City, MO"
    #phone = "1-555-555-1234"
    contactNote = "Dev Tools Engineer"
    profileImage = "img/TechChat.png"
    email = "emanuel.a.falcon@gmail.com"
    description = "Senior Database Administrator with experience adminitrating large scale database systems on Oracle 11g and 12c."
    favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showProjects = true
    showOpenSource = true
    showPublications = true
    showExperience = true
    showEducation = true

    showQr = false

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/emanuel-falcón-8bb28753"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/efalconhndz/"
